variants:
  - name: nominal

  - name: eef_y_neg_04
    eef_delta: [0.0, -0.4, 0.0]
    eef_preposition_steps: 120
    eef_step_size: 1.0
    eef_tolerance: 0.01

  - name: eef_y_neg_02
    eef_delta: [0.0, -0.2, 0.0]
    eef_preposition_steps: 120
    eef_step_size: 1.0
    eef_tolerance: 0.01

  - name: eef_y_pos_02
    eef_delta: [0.0, 0.2, 0.0]
    eef_preposition_steps: 120
    eef_step_size: 1.0
    eef_tolerance: 0.01

  - name: eef_y_pos_04
    eef_delta: [0.0, 0.4, 0.0]
    eef_preposition_steps: 120
    eef_step_size: 1.0
    eef_tolerance: 0.01
